[package]
name = "vobject"
description = "Simple VObject parsing library."
version = "0.1.0"
authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"

[lib]
name = "vobject"
path = "src/vobject/lib.rs"

[dependencies]
peg = "0.1.3"
